name: "DiffuseSlide"
version: "DiffuseSlide 4x"

# input_image_path: "assets/Darth_Vader.jpg"
# input_image_path: "assets/house.jpg"
input_image_path: "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/svd/rocket.png"

output_path: "result/"
output_file_name: "sample" 

diffusion:
  pretrained_model_name_or_path: "stabilityai/stable-video-diffusion-img2vid"
  seed: 17
  num_frames: 14
  num_inference_steps: 25
  fps: [7, 7]
  decode_chunk_size: 7
  
  save_origin: True
  save_interpol: True
  
  interpolation_enable: [False, True]
  num_interpolations: 3

  split_enable: [False, True]

  height: 576 
  width:  1024 

  denoise_start: [0, 17]
  denoise_end: [25, 25] 

  g_scale: 0.2

  fuse_enable: [False, True]
  fuse_threshold: [0, 3]
  fuse_step: [0, 5]

  noise_aug_strength: 0.02
  num_videos_per_prompt: 1
  do_classifier_free_guidance: True
  motion_bucket_id: [128, 32]
  batch_size: 1
  min_guidance_scale: [1.0, 1.0]
  max_guidance_scale: [3.0, 3.0]

  noise_refine: True

  metrics: True

  model_cpu_offload: False
  torch_compile_unet: False

fft:
  fft_enable: False
  filter_type: "gaussian"
  n: 4
  d_s: 0.25
  d_t: 0.25

sliding_windows:
  kernel_size: [0, 14]
  stride: [0, 8]